/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Acueducto2.glb --types 
*/

import * as THREE from 'three'
type GLTFAction = THREE.AnimationClip;
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Isla: THREE.Mesh
    Agua: THREE.Mesh
    Roca_1: THREE.Mesh
    Roca_2: THREE.Mesh
    Roca_3: THREE.Mesh
    Arbol: THREE.Mesh
    Arbol001: THREE.Mesh
    Arbol002: THREE.Mesh
    Arbol003: THREE.Mesh
    Arbol004: THREE.Mesh
    Arbol005: THREE.Mesh
    Roca_2001: THREE.Mesh
    Roca_1001: THREE.Mesh
    Acueducto: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Acueducto2(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/Acueducto2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Isla.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Agua.geometry} material={materials['Material.003']} position={[9.859, 0.283, -0.003]} />
      <mesh geometry={nodes.Roca_1.geometry} material={materials['Material.003']} position={[9.132, 0.633, -1.666]} />
      <mesh geometry={nodes.Roca_2.geometry} material={materials['Material.003']} position={[9.126, 0.616, 1.495]} rotation={[0.146, 0.109, -0.06]} scale={1.48} />
      <mesh geometry={nodes.Roca_3.geometry} material={materials['Material.003']} position={[8.532, 0.552, -0.287]} rotation={[2.944, 0.744, -3.051]} scale={1.714} />
      <mesh geometry={nodes.Arbol.geometry} material={materials['Material.003']} position={[-5.304, 3.027, -2.26]} rotation={[0.082, -0.188, 0.015]} scale={[0.778, 0.426, 0.778]} />
      <mesh geometry={nodes.Arbol001.geometry} material={materials['Material.003']} position={[-6.633, 2.354, -3.723]} rotation={[2.941, 1.156, -2.958]} scale={[0.612, 0.335, 0.612]} />
      <mesh geometry={nodes.Arbol002.geometry} material={materials['Material.003']} position={[-4.965, 2.354, -6.719]} rotation={[2.941, 1.156, -2.958]} scale={[0.612, 0.335, 0.612]} />
      <mesh geometry={nodes.Arbol003.geometry} material={materials['Material.003']} position={[-4.965, 3.98, 7.182]} rotation={[2.941, 1.156, -2.958]} scale={[0.612, 0.548, 0.615]} />
      <mesh geometry={nodes.Arbol004.geometry} material={materials['Material.003']} position={[-6.191, 3.027, 5.607]} rotation={[0.082, -0.188, 0.015]} scale={[0.778, 0.426, 0.778]} />
      <mesh geometry={nodes.Arbol005.geometry} material={materials['Material.003']} position={[2.255, 2.354, -3.723]} rotation={[2.941, 1.156, -2.958]} scale={[0.612, 0.335, 0.612]} />
      <mesh geometry={nodes.Roca_2001.geometry} material={materials['Material.003']} position={[-8.541, 0.616, 1.495]} rotation={[0.146, 0.109, -0.06]} scale={1.48} />
      <mesh geometry={nodes.Roca_1001.geometry} material={materials['Material.003']} position={[3.926, 0.633, -3.152]} />
      <mesh geometry={nodes.Acueducto.geometry} material={materials.Material} position={[-0.76, 3.933, 7.083]} rotation={[0, Math.PI / 2, 0]} scale={0.733} />
    </group>
  )
}

useGLTF.preload('/Acueducto2.glb')
